apiVersion: v1
kind: Namespace
metadata:
  annotations:
    cattle.io/status: '{"Conditions":[{"Type":"ResourceQuotaInit","Status":"True","Message":"","LastUpdateTime":"2025-05-27T08:17:35Z"},{"Type":"InitialRolesPopulated","Status":"True","Message":"","LastUpdateTime":"2025-05-27T08:17:40Z"}]}'
    field.cattle.io/projectId: local:p-hskql
    lifecycle.cattle.io/create.namespace-auth: "true"
    management.cattle.io/no-default-sa-token: "true"
  creationTimestamp: "2025-05-27T08:17:13Z"
  deletionTimestamp: "2025-05-27T09:28:43Z"
  labels:
    field.cattle.io/projectId: p-hskql
    kubernetes.io/metadata.name: cattle-system
    name: cattle-system
  name: cattle-system
  resourceVersion: "19535"
  uid: 6d29aff0-4202-45cb-8844-7cf4df2cccda
spec:
  finalizers:
  - kubernetes
status:
  conditions:
  - lastTransitionTime: "2025-05-27T09:28:49Z"
    message: 'Discovery failed for some groups, 1 failing: unable to retrieve the
      complete list of server APIs: ext.cattle.io/v1: stale GroupVersion discovery:
      ext.cattle.io/v1'
    reason: DiscoveryFailed
    status: "True"
    type: NamespaceDeletionDiscoveryFailure
  - lastTransitionTime: "2025-05-27T09:28:49Z"
    message: All legacy kube types successfully parsed
    reason: ParsedGroupVersions
    status: "False"
    type: NamespaceDeletionGroupVersionParsingFailure
  - lastTransitionTime: "2025-05-27T09:28:49Z"
    message: 'Failed to delete all resource types, 1 remaining: Internal error occurred:
      failed calling webhook "rancher.cattle.io.secrets": failed to call webhook:
      Post "https://rancher-webhook.cattle-system.svc:443/v1/webhook/mutation/secrets?timeout=15s":
      service "rancher-webhook" not found'
    reason: ContentDeletionFailed
    status: "True"
    type: NamespaceDeletionContentFailure
  - lastTransitionTime: "2025-05-27T09:28:51Z"
    message: All content successfully removed
    reason: ContentRemoved
    status: "False"
    type: NamespaceContentRemaining
  - lastTransitionTime: "2025-05-27T09:28:49Z"
    message: All content-preserving finalizers finished
    reason: ContentHasNoFinalizers
    status: "False"
    type: NamespaceFinalizersRemaining
  phase: Terminating
