apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory # Let's Encrypt Production Server
    email: "dkatulreg@gmail.com"                         # Your email for ACME registration
    privateKeySecretRef:
      name: letsencrypt-prod-account-key                  # Secret to store ACME account private key
    solvers:
      - http01:
          ingress:
            ingressClassName: traefik                     # Use Traefik for solving HTTP01 challenges

